# Deploys dev stage
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run dev --host 0.0.0.0
